live:
  - name: Ethereum
    networks:
      - name: Mainnet (Infura)
        chainid: 1
        id: mainnet
        host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Ropsten (Infura)
        chainid: 3
        id: ropsten
        host: https://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-ropsten.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Rinkeby (Infura)
        chainid: 4
        id: rinkeby
        host: https://rinkeby.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-rinkeby.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Goerli (Infura)
        chainid: 5
        id: goerli
        host: https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-goerli.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Kovan (Infura)
        chainid: 42
        id: kovan
        host: https://kovan.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-kovan.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
development:
  - name: Ganache-CLI
    id: development
    host: http://172.15.0.3:8545    